### ISSUE TITLE
Issues with interruption

### ISSUE THREAD

**Issue by algernon** [keyboardio/Akela-OneShot#4]
When a one-shot mod or layer is interrupted (it is more visible with layers, though), and the interrupting key is held longer than a cycle or two, then it gets registered again. So if on the base layer, there's `A`, and on a one-shot layer it becomes `B`, and I tap the layer key, then tap this key slowly, then both `B` and `A` will register.

There should be a short timeout where the interrupting key is masked out after an interruption, to avoid these issues. Or perhaps a mask until release... but that may interfere with holding. But perhaps that's an easier compromise?

**Comment by cdisselkoen** [comment]
Would the more-straightforward fix be to just keep the modifier/layer key held until the interrupting key is released?  The idea being that in the above example, if you press the interrupting key too slowly it would just start repeating B (subject to whatever normal repeating behavior is in place).  No masking required at all.

This would fix #11 - would it also serve as an adequate alternate fix for #4?  I.e. we would revert the existing fix with the masking behavior, and use this instead to fix #11 and re-fix #4 simultaneously.

**Comment by algernon** [comment]
I think I considered something like that before, and a very early version of OneShot may even have worked that way. But there's a catch: what happens if you press another key while holding the interruptor?

Case in point, tap `OSM(LeftShift)`, tap and hold `a`, and you get a lot of repeated `AAAAA`s. So far so good. Now press `b` too, and you get a lot of `BBBB`s, even though that is the second key you pressed after a - supposedly - one-shot modifier. I don't think this would be a desirable behaviour. It would be too confusing.

**Comment by cdisselkoen** [comment]
I'm not sure, as a user, what my expected behavior would be if I was holding `AAAAA` with a OneShot Shift, and then without releasing `A` tapped B.  This seems an obscure enough case that it's unclear what the user would be expecting.

Even on keyboards I've used before, pressing a key while holding another (non-modifier) key can create strange behavior - for instance, holding left arrow, keeping it pressed, and then pressing and holding right arrow would send a single right-arrow event, but neither left nor right arrow would repeat (despite both keys being held - or even if one was subsequently released) until both keys were released.  (My Model 01 has a different behavior, which I like better, namely the second key will continue to repeat and the first one will be ignored.)

I guess the point of this is to say that this is an ambiguous corner case, so I think it might be an acceptable compromise in exchange for simple fixes for #10 and #11.  Users would learn that to cancel a OneShot, you have to fully release both the OneShot and the (first) affected key - the OneShot will stay active until the affected key is released.

**Comment by algernon** [comment]
I'd like to explore other alternatives before applying your proposed behaviour. To offer an example, oneshots in QMK in the mentioned case produce `Aaaaaabbbbbbbb` - and that would be the most logical thing I believe. If we can get there with reasonable ease, we should.

**Comment by cdisselkoen** [comment]
Sure, I can agree with that.  I'd also like to propose/ensure that if the oneshot is actually _held_, the behavior should be `AAAAAABBBBBBBBB`.

**Comment by algernon** [comment]
Agreed!

**Comment by cdisselkoen** [comment]
... So I'm still a little bit confused - how is the QMK behavior you described different from the buggy behavior first reported in #4?  Going back to OP's example, if we hold `B` long enough for it to start repeating, don't we expect it to start repeating `AAAA` not `BBBB`?  How is the fix we're looking for different from a simple revert of the original fix for #4?

**Comment by algernon** [comment]
In QMK's case, OneShot layers apply a mask, so #4 is covered, but OneShot modifiers don't, so repeat works, at least as far as I can tell.
